server:
  port: 8761
  address: 0.0.0.0


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    service-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/