server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: CRAWLER-SERVICE1
              uri: lb://CRAWLER-SERVICE1
              predicates:
                - Path=/jobs/**


            - id: AUTH-SERVICE
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: ONBOARD-SERVICE
              uri: lb://ONBOARD-SERVICE
              predicates:
                - Path=/onboard/**

            - id: LEADMANAGEMENT
              uri: lb://LEADMANAGEMENT
              predicates:
                - Path=/api/leads/**


      cloud:
        config:
          enabled: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

