server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: 8767780674

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 998701934160-d9mkdca2eglqs6tp4hvodnosgtab1v7f.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8082/login/oauth2/code/google
            scope:
              - openid
              - email
              - profile

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  application:
    name: AUTH-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-service: true
    service-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka







