server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crawler_db
    username: postgres
    password: 8767780674

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-service: true
    service-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

webdriver:
  chrome:
    driver: ./drivers/chromedriver

logging:
  level:
    com.ob.example: INFO